<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.vaadin.walking-skeleton</groupId>
        <artifactId>walking-skeleton-root</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>walking-skeleton-assembly</artifactId>
    <packaging>pom</packaging>
    <name>Walking Skeleton Assembly</name>
    <description>
        Uses Maven Assembly Plugin to create zip-files of the Walking Skeleton, ready to be used in projects.
    </description>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.7.1</version>
                <configuration>
                    <finalName>walking-skeleton</finalName>
                    <descriptors>
                        <descriptor>src/assembly/empty-skeleton.xml</descriptor>
                        <descriptor>src/assembly/flow-skeleton.xml</descriptor>
                    </descriptors>
                    <attach>false</attach>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>xml-maven-plugin</artifactId>
                <version>1.1.0</version>
                <executions>
                    <execution>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>transform</goal>
                        </goals>
                        <configuration>
                            <transformationSets>
                                <transformationSet>
                                    <dir>${basedir}/../walking-skeleton</dir>
                                    <includes>
                                        <include>pom.xml</include>
                                    </includes>
                                    <stylesheet>src/assembly/base-pom-transform.xsl</stylesheet>
                                    <outputDir>${basedir}/target/nonempty-project</outputDir>
                                </transformationSet>
                                <transformationSet>
                                    <dir>${basedir}/../walking-skeleton</dir>
                                    <includes>
                                        <include>pom.xml</include>
                                    </includes>
                                    <stylesheet>src/assembly/empty-pom-transform.xsl</stylesheet>
                                    <outputDir>${basedir}/target/empty-project</outputDir>
                                </transformationSet>
                            </transformationSets>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>