<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.vaadin.walking-skeleton</groupId>
        <artifactId>walking-skeleton-root</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>walking-skeleton-assembly</artifactId>
    <packaging>pom</packaging>
    <name>Walking Skeleton Assembly</name>
    <description>
        Uses Maven Assembly Plugin to create zip-files of the Walking Skeleton, ready to be used in projects.
    </description>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.7.1</version>
                <configuration>
                    <finalName>walking-skeleton</finalName>
                    <descriptors>
                        <descriptor>src/assembly/empty-skeleton.xml</descriptor>
                        <descriptor>src/assembly/flow-skeleton.xml</descriptor>
                        <descriptor>src/assembly/hilla-skeleton.xml</descriptor>
                        <descriptor>src/assembly/hybrid-skeleton.xml</descriptor>
                    </descriptors>
                    <attach>false</attach>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>com.igormaznitsa</groupId>
                <artifactId>jcp</artifactId>
                <version>7.1.2</version>
                <executions>
                    <execution>
                        <id>preprocess-hilla</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>preprocess</goal>
                        </goals>
                        <configuration>
                            <vars>
                                <ui.framework>hilla</ui.framework>
                            </vars>
                            <target>${basedir}/target/generated-sources/hilla</target>
                        </configuration>
                    </execution>
                    <execution>
                        <id>preprocess-flow</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>preprocess</goal>
                        </goals>
                        <configuration>
                            <vars>
                                <ui.framework>flow</ui.framework>
                            </vars>
                            <target>${basedir}/target/generated-sources/flow</target>
                        </configuration>
                    </execution>
                </executions>
                <configuration>
                    <sources>
                        <source>${basedir}/../walking-skeleton/src/main/java</source>
                    </sources>
                    <keepLines>false</keepLines>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-antrun-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>prepare-package</phase>
                        <configuration>
                            <target>
                                <!-- Replace hybrid view route in Flow only starter -->
                                <replace token="task-list-flow" value="" dir="target/generated-sources/flow">
                                    <include name="**/TodoView.java"/>
                                </replace>
                                <!-- Replace hybrid view name in Flow only starter -->
                                <replace token="Task List Flow" value="Task List" dir="target/generated-sources/flow">
                                    <include name="**/TodoView.java"/>
                                </replace>
                            </target>
                        </configuration>
                        <goals>
                            <goal>run</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>