name: Validate assemblies
on:  pull_request

jobs:
  validate:
    name: Validate assemblies
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: '3.9.6'
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Spotless check
        run: |
          mvn -ntp -B spotless:check
      - name: Build template and assemblies
        run: |
          mvn -ntp -B clean package
      - name: Build each assembly
        shell: bash
        run: |
          cd assembly/target
          for ASSEMBLY in empty flow hilla hybrid; do
            echo "> ==================== Building walking-skeleton-${ASSEMBLY} ..."
            unzip -q walking-skeleton-${ASSEMBLY}
            cd walking-skeleton
            mvn -ntp -B -q clean package
            cd ..
            rm -rf walking-skeleton
            echo "> ==================== Done"
          done
